Ensure tests can run
I observed that when I run the tests locally, I see errors like this:

```
NoMethodError:
       undefined method 'parse' for class CGI
```

There are a few specs which depend on `CGI.parse` but we never actually
require the cgi gem anywhere in this codebase. In the past, everything
Just Worked because one of our direct dependencies did require it, so it
was loaded by the time we got here. But now, on a freshly-regenerated
`Gemfile.lock`, it is no longer auto-required by one of our direct
dependencies.

No worries, we can load it ourselves.